# Model
device: 1
alg_name: "MEND"
name: Qwen/Qwen-VL
model_name: qwen-vl
model_class: qwen-vl
tokenizer_class: QWenTokenizer
tokenizer_name: Qwen/Qwen-VL
inner_params:
- transformer.h.29.mlp.w1.weight
- transformer.h.29.mlp.w2.weight
- transformer.h.29.mlp.c_proj.weight
- transformer.h.30.mlp.w1.weight
- transformer.h.30.mlp.w2.weight
- transformer.h.30.mlp.c_proj.weight
- transformer.h.31.mlp.w1.weight
- transformer.h.31.mlp.w2.weight
- transformer.h.31.mlp.c_proj.weight

# Method
alg: MEND
lr: 1e-6
edit_lr: 1e-4
lr_lr: 1e-4
lr_scale: 1.0
seed: 42
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
train_base: False
no_grad_layers: null
one_sided: False
n_hidden: 1
hidden_dim: null
init: id
norm: True
combine: True
x_only: False
delta_only: False
act: relu
rank: 1920
mlp_class: IDMLP
shared: True
# archive: /home/zhonghaitian/MLLM/EasyEdit/results/qwenvl_port_final_1.30/models/MEND/qwen-vl-step_40000.pt
archive: /home/v-hazhong/Models/VLKEB/qwen-vl-mend-step_45000.pt
# inference_mode: fp32
# eval_path: /home/zhonghaitian/MLLM/EasyEdit/results/qwenvl_port_final_1.30/models/MEND/eval_results.txt

# Train
batch_size: 1
model_save_pt: 5000
silent: False
#max_epochs: 1
max_iters: 50000
log_interval: 100
eval_log_interval: 1000
final_eval: True
val_interval: 5000
early_stop_patience: 20000
early_stop_key: "loss/total_edit_val"
eval_only: True
half: False
debug: False
save: False
verbose: True

val_batch_size: 1
accumulate_bs: 2
val_steps: 500 # only for debug
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results

# Multimodal
qformer_checkpoint: None
qformer_name_or_path: None
state_dict_file: None

# image
coco_image: /data0/huanghan/datasets/mmkb/image-graph_images/
rephrase_image: /data0/huanghan/datasets/mmkb/image-graph_images/