device: 0

name: /data0/zhonghaitian/Models/Qwen-VL
model_name: qwen-vl
model_class: qwen-vl
small_name: /data0/zhonghaitian/Models/Qwen-7b
tokenizer_class: QWenTokenizer
tokenizer_name: /data0/zhonghaitian/Models/Qwen-VL
cls_name: /data0/huanghan/projects/EasyEdit/hugging_cache/distilbert-base-cased
cls_class: AutoModel 
inner_params:
- transformer.h.29.mlp.w1.weight
- transformer.h.29.mlp.w2.weight
- transformer.h.29.mlp.c_proj.weight
- transformer.h.30.mlp.w1.weight
- transformer.h.30.mlp.w2.weight
- transformer.h.30.mlp.c_proj.weight
- transformer.h.31.mlp.w1.weight
- transformer.h.31.mlp.w2.weight
- transformer.h.31.mlp.c_proj.weight


# Method
alg: SERAC_MULTI
lr: 1e-5
edit_lr: 1e-2
seed: 0
lr_lr: 0.0
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
final_eval: True
supervised: False
train_base: False
no_grad_layers: null
soft_weighting: False
checkpoint_grad: False
cross_attend: False
cos: False
freeze: null
square: True
bound_embeds: False
use_all_negatives: False
freeze_cntr: False
dist_heads: 1
lora: null
archive: null

batch_size: 1
model_save_pt: 5000
edit_bs: 1
silent: False
#max_epochs: 1
max_iters: 50000
log_interval: 100
val_interval: 5000
early_stop_patience: 10000
early_stop_key: "loss/total_edit_val"
eval_only: False
half: False
save: False
debug: False
log_errors: False
unlikelihood: True


val_batch_size: 1
accumulate_bs: 1
val_steps: 1000
opt: Adam
grad_clip: 100.

# Output
results_dir: /data0/zhonghaitian/Projects/MLLM Editing/test_results/qwenvl_port_final_3.6

# Multimodal
qformer_checkpoint: null
qformer_name_or_path: null
state_dict_file: null
# pretrained_ckpt: null

# image
coco_image: "/data0/huanghan/datasets/mmkb/image-graph_images/"
rephrase_image: "/data0/huanghan/datasets/mmkb/image-graph_images/"